### PR TITLE
Symfony 3 Patch

### PR DESCRIPTION
**Pull request by insekticid**

### CODE REVIEW

**Comment by isometriks** [comment]
Thank you for this. I think I would still like to keep a BC layer for 2.7+ so I may take this and add some more commits to it unless you wanted to add that in. Should just need a compiler pass to change tags and then maybe something like FOS User does: https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Util/LegacyFormHelper.php to get the form type in internal classes.

**Comment by insekticid** [comment]
It is not necessary, just create 1.0 branch with support for old Symfony 2.+
Master should be synced with latest Symfony 3+

**Comment by mipapo** [comment]
Would be great if a 3.0 branch would be created!

**Comment by isometriks** [comment]
thanks @insekticid Symfony 3 compatibility added in ~1.0

**Pull request merged**
