### PR TITLE
Drop SF 4 and add SF 7 support

### LINKED ISSUE #34: Drop support for symfony 4.4
[Symfony 4.4](https://symfony.com/releases/4.4) is coming to [the end of it's security fix support](https://endoflife.date/symfony), it is not recommended to use this version anymore, 5.4 is the current LTS version and 6.4 is just around the corner.
I'd be happy to drop 4.4 support and release a new version so that 4.4 users can keep using this bundle in it's 1.1.0 version, while we add new updates for 5.4 / 6.* / 7.0 only.
That will make it easier for developers who want to contribute, since juggling with compatibility isn't easy (and there's a big gap between 4.4 and 7.0).

### PR DESCRIPTION
**Pull request by maelanleborgne**
Closes #34

### CODE REVIEW

**Comment by ThomasLandauer** [comment]
Ping @isometriks

**Comment by maelanleborgne** [comment]
@ThomasLandauer I'd be happy to merge this PR (as well as #33 ) but since I'm the author I need a review from another maintainer (@isometriks ?) before I can do so.

**Review by isometriks — APPROVED** [review]

**Comment by ThomasLandauer** [comment]
@maelanleborgne @isometriks Please tag a new version, so people can actually use this :-)

**Comment by isometriks** [comment]
All set. I removed the 1 approval as well so you should be able to self merge now. I'll look into giving you access to do releases too.

**Pull request merged**
